language: python
sudo: true
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install pep8 pylint pytest
script:
    - make test
after_success:
      - bash <(curl -s https://codecov.io/bash)
